### ISSUE TITLE
Add Factory<>

### ISSUE THREAD

**Issue by michal-ciechan** [sungam3r/SteroidsDI#1]
Personally, when I see/hear `Defer<T>`, I think of `Lazy<T>`, where it will cache the value for its lifetime. I know this is well documented that it does not, but I still think anyone looking through code that uses this, and is familiar with `Lazy`, will potentially make wrong assumptions. I did until reading the docs. (I don't expect new joiners to read the docs for all 30+ libraries we use in our projects before contributing!).

Especially considering the usage is via a `T Value { get; }` prop which is the same as `Lazy`. I think it would be worth adding one of the following (which would work exactly same way as `Defer<T>`:

* `Factory<T>.Create()` 
* `Provider<T>.Get()`

If you think its worth adding, let me know, more than happy to create a PR, otherwise just close the issue.

Thanks for your work by the way!

**Comment by sungam3r** [comment]
Are you talking about just aliases for an existing APIs? How will it look from the caller side?

When I chose the name for `Defer`, I tried to select the one that most closely reflects its meaning. And as you correctly noted, I tried to describe my intentions in the documentation as detailed as possible.

**Comment by sungam3r** [comment]
I think that we can add note about the differences between `Defer` and `Lazy` in the FAQ.

**Comment by michal-ciechan** [comment]
To be honest, its pretty well documented already so closing this issue
